const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Plugins.Keyboard,
		C3.Plugins.HTMLElement,
		C3.Plugins.Button,
		C3.Plugins.Camera3D,
		C3.Behaviors.Platform,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Text,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Button.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.ScriptsInEvents.EventSheet2_Event2_Act1,
		C3.ScriptsInEvents.Macos_Event5,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.ScriptsInEvents.Playerscript_Event1_Act1,
		C3.Plugins.Text.Acts.SetVisible
	];
};
self.C3_JsPropNameTable = [
	{"8Direction": 0},
	{Sprite: 0},
	{MacBook: 0},
	{Keyboard: 0},
	{HTMLElement: 0},
	{Button: 0},
	{Sprite2: 0},
	{Button2: 0},
	{Sprite3: 0},
	{"3DCamera": 0},
	{Platform: 0},
	{Sprite4: 0},
	{Solid: 0},
	{TiledBackground: 0},
	{Text: 0},
	{Button3: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Button4: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Text2: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Button5: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Button6: 0},
	{"8Direction2": 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{app: 0},
	{Text3: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	MacBook: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	HTMLElement: class extends self.IHTMLElementInstance {},
	Button: class extends self.IButtonInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Button2: class extends self.IButtonInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	_3DCamera: class extends self.IInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Text: class extends self.ITextInstance {},
	Button3: class extends self.IButtonInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Button4: class extends self.IButtonInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Button5: class extends self.IButtonInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Button6: class extends self.IButtonInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	app: class extends self.IButtonInstance {},
	Text3: class extends self.ITextInstance {}
}